language: python
install:
  - pip install coveralls
  - python setup.py install
python:
  - "2.7"
  - "3.4"
  - "3.5"
script:
  - coverage run normalization/ufonormalizer.py -t
  - python setup.py test
after_success:
  coveralls
