language: python
install:
  - pip install coveralls
  - python setup.py install
python:
  - "2.7"
  - "3.4"
script:
  - coverage run normalization/ufonormalizer.py -t
  - ufonormalizer -t | tee /dev/stderr | grep "\*\*\*Test Failed\*\*\*"; if [[ ${PIPESTATUS[2]} == "0" ]]; then exit 1 ; fi
after_success:
  coveralls
